SELECT * FROM PRODUCTS
order by PRODUCTPRICE DESC
LIMIT 1  #LIMITING TO JUST ONE ROW

P1 - 15
P2 - 18
P3 - 18
P5 - 18
P4 - 11

OUTPUT SHOULD BE 
P2, P3, P5 # SHOULD RETURN 3 ROWS

SELECT DISTINCT PRODUCTNAME, PRODUCTPRICE FROM PRODUCTS
WHERE PRODUCTPRICE = (SELECT MAX(PRODUCTPRICE) FROM PRODUCTS) #FILTERS ALL THE ROWS HAVING HIGHEST PRODUCT PRICE DYNAMICALLY

#FINDOUT THE 2ND HIGHEST PRICED PRIDUCT
SELECT MAX(PRODUCTPRICE) FROM PRODUCTS
WHERE PRODUCTPRICE < (SELECT MAX(PRODUCTPRICE) FROM PRODUCTS)


#FINDOUT PRODUCTNAME, PRODUCTPRICE FOR THE 2ND HIGHEST PRICED PRIDUCT
SELECT PRODUCTNAME, PRODUCTPRICE FROM PRODUCTS
WHERE PRODUCTPRICE = (SELECT MAX(PRODUCTPRICE) FROM PRODUCTS
						WHERE PRODUCTPRICE < 
							(SELECT MAX(PRODUCTPRICE) FROM PRODUCTS)
                        )

#FINDOUT PRODUCTNAME, PRODUCTPRICE FOR THE 3RD HIGHEST PRICED PRIDUCT
SELECT PRODUCTNAME, PRODUCTPRICE FROM PRODUCTS
WHERE PRODUCTPRICE = (SELECT MAX(PRODUCTPRICE) FROM PRODUCTS					#SUBQUERY 3
						WHERE PRODUCTPRICE < 
							(SELECT MAX(PRODUCTPRICE) FROM PRODUCTS						#SUBQUERY 2
								WHERE PRODUCTPRICE < 
									(SELECT MAX(PRODUCTPRICE) FROM PRODUCTS)					# SUBQUERY 1
							)
					 )
#NOTE:- WE SHOULD NOT MAKE THIS APPROACH TO FIND THE Nth highest price which will include n subqueries, in that case we have a better 
#		approach called Windows Functions

HOMEWORK
---------
SELECT T.REGION, SUB.TOTAL_RETURN_QUANTITY
FROM TERRITORIES T
JOIN (
		SELECT R.TERRITORYKEY,
			SUM(R.RETURNQUANTITY) AS TOTAL_RETURN_QUANTITY
		FROM RETURNS R
        GROUP BY R.TERRITORYKEY
        ORDER BY 1
	 ) SUB 
     ON T.SALESTERRITORYKEY = SUB.TERRITORYKEY
ORDER BY SUB.TOTAL_RETURN_QUANTITY DESC;
	
#OR
    
SELECT REGION, SUM(RETURNQUANTITY) AS TOTAL_RETURN_QUANTITY
FROM TERRITORIES T
JOIN returns
ON SALESTERRITORYKEY = TERRITORYKEY
group by 1
ORDER BY 2 DESC

#FINDOUT PRODUCT NAMES AND COSTS OF ALL THE HIGHEST AND LOWEST PRICED PRIDUCT
SELECT PRODUCTNAME, PRODUCTPRICE FROM PRODUCTS
WHERE PRODUCTPRICE = (SELECT MAX(PRODUCTPRICE) FROM PRODUCTS) 
		OR 
	  PRODUCTPRICE = (SELECT MIN(PRODUCTPRICE) FROM PRODUCTS)