DROP TABLE IPL_MATCH;

-- 		INPUT		--

CREATE TABLE IPL_MATCH(
TEAM1 VARCHAR(10),
TEAM2 VARCHAR(10),
WINNER VARCHAR(10)
);

INSERT INTO IPL_MATCH
VALUES 
('RCB',	'CSK',	'RCB'),
('CSK',	'MI',	'MI'),
('KKR',	'RCB',	'RCB'),
('KKR',	'DC',	'DC'),
('PBKS','GT',	'GT'),
('RCB',	'MI',	'RCB'),
('RR',	'PBKS',	NULL),
('GT',	'SRH',	'GT'),
('SRH',	'LSG',	'SRH'),
('RR',	'CSK',	'RR');

SELECT * FROM IPL_MATCH;

-- 					  EXPECTED OUTPUT
-- 					  ---------------
-- teams | # of wins  | # of losses | # of draws	|  #draws/#wins
-- RCB	 |		2	  |		0		|	0			|	0/2
-- KKR	 |		0	  |		2		|	0			|	0


WITH TEAMS AS
(SELECT TEAM1 AS TEAM_NAME FROM IPL_MATCH
UNION
SELECT TEAM2 AS TEAM_NAME FROM IPL_MATCH),

WINNER_CTE AS (
SELECT TEAM_NAME, TEAM1, TEAM2, WINNER, 
	CASE
		WHEN TEAM_NAME = WINNER THEN 1
		ELSE 0 
		END AS WINNER_COUNT_TEAM,
    CASE 
		WHEN WINNER IS NULL THEN 1
        ELSE 0
        END AS DRAW
FROM IPL_MATCH I
INNER JOIN TEAMS T 
	ON TEAM_NAME = TEAM1 OR TEAM_NAME = TEAM2 ),

WINNERS AS 
(SELECT 
	TEAM_NAME,
    SUM(WINNER_COUNT_TEAM) AS NO_OF_WINS
FROM WINNER_CTE
GROUP BY TEAM_NAME
),
    
LOSERS AS (
SELECT TEAM_NAME, COUNT(TEAM_NAME) AS LOSER_COUNT FROM WINNER_CTE 
WHERE TEAM_NAME != WINNER AND WINNER IS NOT NULL 
GROUP BY TEAM_NAME
),

DRAW AS (
SELECT TEAM_NAME, COUNT(TEAM_NAME) AS DRAW_COUNT FROM WINNER_CTE 
WHERE DRAW = 1
GROUP BY TEAM_NAME
),

FINAL AS 
(SELECT 
	WC.TEAM_NAME AS TEAM_NAME,
    COALESCE(NO_OF_WINS, 0) AS NO_OF_WINS,
	COALESCE(LOSER_COUNT, 0) AS NO_OF_LOSSES,
	COALESCE(DRAW_COUNT, 0) AS NO_OF_DRAWS
FROM WINNER_CTE WC 
LEFT JOIN WINNERS W ON WC.TEAM_NAME = W.TEAM_NAME
LEFT JOIN LOSERS L ON WC.TEAM_NAME = L.TEAM_NAME
LEFT JOIN DRAW D ON WC.TEAM_NAME = D.TEAM_NAME
)

-- SELECT * FROM TEAMS
-- SELECT * FROM WINNER_CTE
-- SELECT * FROM WINNERS
-- SELECT * FROM LOSERS
-- SELECT * FROM DRAW
-- SELECT * FROM FINAL

SELECT 
	DISTINCT TEAM_NAME,
	NO_OF_WINS,
	NO_OF_LOSSES,
	NO_OF_DRAWS,
	COALESCE(CONCAT(NO_OF_DRAWS,'/', NO_OF_WINS), 0) AS NO_OF_DRAWS_OR_WINS
FROM FINAL
ORDER BY NO_OF_WINS DESC, NO_OF_LOSSES ASC, TEAM_NAME ASC;
