SHOW VARIABLES WHERE Variable_name = 'hostname';
SHOW VARIABLES LIKE 'hostname';
SHOW VARIABLES WHERE Variable_name = 'port';
SELECT @@hostname, @@port;
SELECT CURRENT_USER();
SELECT USER();
ALTER USER 'root'@'localhost' IDENTIFIED BY 'AzSQL@19';
FLUSH PRIVILEGES;
-- CREATE USER 'root'@'%' IDENTIFIED BY 'AzSQL@19';
ALTER USER 'root'@'%' IDENTIFIED BY 'AzSQL@19';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;


